FROM ubuntu:lunar

ARG USER_ID
ARG GROUP_ID
ARG USERNAME=ubuntu
ARG HOME=/home/${USERNAME}

ARG GIT_USERNAME
ARG GIT_USEREMAIL

RUN apt update && apt install -y git wget xz-utils && apt clean -y
RUN usermod --uid ${USER_ID} --gid ${GROUP_ID} ${USERNAME}

USER ${USERNAME}
ARG APPS_DIR=${HOME}/applications
ARG WORK_DIR=${HOME}/work

WORKDIR ${HOME}
COPY --chown=${USER_ID}:${GROUP_ID} config .config

ENV PATH=${APPS_DIR}/bin:${APPS_DIR}/nushell:${APPS_DIR}/helix:${APPS_DIR}:${PATH}

WORKDIR ${APPS_DIR}
RUN mkdir helix && wget -qO- https://github.com/helix-editor/helix/releases/download/23.05/helix-23.05-x86_64-linux.tar.xz | tar -xJ -C helix --strip-components 1
RUN mkdir nushell && wget -qO- https://github.com/nushell/nushell/releases/download/0.80.0/nu-0.80.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz -C nushell --strip-components 1

RUN mkdir bin && wget -q -O ${APPS_DIR}/bin/pueue https://github.com/Nukesor/pueue/releases/download/v3.1.2/pueue-linux-x86_64 && chmod +x ${APPS_DIR}/bin/pueue
RUN wget -q -O ${APPS_DIR}/bin/pueued https://github.com/Nukesor/pueue/releases/download/v3.1.2/pueued-linux-x86_64 && chmod +x ${APPS_DIR}/bin/pueued
RUN pueued --daemonize

RUN git config --global user.name "${GIT_USERNAME}" && git config --global user.email "${GIT_USEREMAIL}"

WORKDIR ${WORK_DIR}
CMD ["nu", "--execute", "pueued --daemonize"]
