FROM ubuntu:lunar

ARG HOME=/root
ARG APPS_DIR=${HOME}/applications
ARG WORK_DIR=${HOME}/work

ENV DEBIAN_FRONTEND=noninteractive
ENV PATH=${APPS_DIR}/nushell:${APPS_DIR}/helix:${PATH}

WORKDIR ${HOME}

COPY config .config

RUN apt update && apt install -y wget xz-utils && apt clean -y

WORKDIR ${APPS_DIR}

RUN mkdir helix && wget -qO- https://github.com/helix-editor/helix/releases/download/23.05/helix-23.05-x86_64-linux.tar.xz | tar -xJ -C helix --strip-components 1
RUN mkdir nushell && wget -qO- https://github.com/nushell/nushell/releases/download/0.80.0/nu-0.80.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz -C nushell --strip-components 1

WORKDIR ${WORK_DIR}

CMD ["nu"]