FROM razcorerad/cxx.dev

ARG USERNAME=ubuntu
ARG HOME=/home/${USERNAME}

USER root
RUN apt update && apt install -y libglfw3-dev libglew-dev && apt clean -y

USER ${USERNAME}
WORKDIR ${HOME}/downloads
RUN git clone https://github.com/svenstaro/glsl-language-server.git --recursive

WORKDIR ${HOME}/downloads/glsl-language-server
RUN cmake -B build -G Ninja -DCMAKE_INSTALL_PREFIX=${HOME}/applications && ninja -C build install

WORKDIR ${HOME}
RUN rm -fr ${HOME}/downloads

WORKDIR ${HOME}/work
